#!/usr/bin/env python3
"""Port a scaffolded harness to Cursor or Codex.

The harness is generated for Claude Code. Cursor and Codex have their own rule and hook systems, and
both are close enough to Claude Code's that the harness ports rather than being rewritten. This script
reads a repo that has already been scaffolded (it has .claude/rules/ and .claude/hooks/) and emits the
tool-specific files next to it.

    python port.py --target <repo> --tool codex
    python port.py --target <repo> --tool cursor
    python port.py --target <repo> --tool all
    python port.py --self-test          # run the adapter against documented sample payloads

WHAT PORTS, AND WHAT DOES NOT
-----------------------------
Rules port in full. Enforcement ports with two caveats, both honest and documented in the output:

  Codex   PreToolUse hooks are structurally identical to Claude Code's: same {cwd, tool_name,
          tool_input.command} input, same exit-2-to-deny, same hooks.json shape. The Bash-checking
          hooks (guard-main-commit, check-commit-msg, protect-secrets) run unchanged. Codex routes
          file edits through apply_patch with the path inside tool_input.command, not a tool_input.
          file_path, so protect-adr (which reads file_path) is best-effort on Codex.

  Cursor  Events and output differ (beforeShellExecution / beforeReadFile, JSON {"permission":...}),
          so a small adapter normalises Cursor's payload to the shape the existing hooks expect and
          translates their exit code back. afterFileEdit is observational-only in Cursor, so an edit
          to an Accepted ADR cannot be blocked before it happens there - only flagged after.

This wiring is built to each tool's published hook schema. It is unit-tested here against documented
sample payloads, but run one real action in the tool to smoke-test it in your environment.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys

# --------------------------------------------------------------------------- rules: Claude -> Cursor

FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def parse_paths(frontmatter: str) -> list[str]:
    """Pull the `paths:` YAML list out of a rule's frontmatter. Minimal parser - the harness only
    ever emits a flat list of quoted globs, so a full YAML dependency is not warranted."""
    globs: list[str] = []
    in_paths = False
    for line in frontmatter.splitlines():
        if re.match(r"^paths:\s*$", line):
            in_paths = True
            continue
        if in_paths:
            m = re.match(r"^\s*-\s*(.+?)\s*$", line)
            if m:
                globs.append(m.group(1).strip().strip('"').strip("'"))
            elif line.strip() and not line.startswith((" ", "\t")):
                break
    return globs


def to_cursor_rule(text: str) -> str:
    """Convert one .claude rule to a .cursor/rules .mdc.

    no `paths:`  -> alwaysApply: true   (Cursor loads it every turn)
    `paths: [g]` -> globs: g,g          (Cursor auto-attaches on a matching file)
    """
    m = FRONTMATTER.match(text)
    fm, body = (m.group(1), text[m.end():]) if m else ("", text)
    desc = ""
    dm = re.search(r"^description:\s*(.+)$", fm, re.MULTILINE)
    if dm:
        desc = dm.group(1).strip()

    globs = parse_paths(fm)
    out = ["---"]
    if desc:
        out.append(f"description: {desc}")
    if globs:
        out.append(f"globs: {','.join(globs)}")
    else:
        out.append("alwaysApply: true")
    out.append("---")
    out.append("")
    return "\n".join(out) + body.lstrip("\n")


def port_cursor_rules(claude_rules: pathlib.Path, dest: pathlib.Path) -> list[str]:
    written = []
    dest.mkdir(parents=True, exist_ok=True)
    for p in sorted(claude_rules.glob("*.md")):
        out = dest / (p.stem + ".mdc")
        out.write_text(to_cursor_rule(p.read_text(encoding="utf-8")), encoding="utf-8")
        written.append(out.name)
    return written


# --------------------------------------------------------------------------- hooks

# The Bash-matching hooks that need no per-payload adaptation on Codex.
BASH_HOOKS = ["guard-main-commit", "check-commit-msg", "protect-secrets"]
# Hooks that inspect a file path.
FILE_HOOKS = ["protect-adr", "protect-secrets"]

CURSOR_ADAPTER = r'''#!/usr/bin/env python3
# Cursor hook adapter (generated by port.py). Normalises Cursor's hook payload to the shape the
# harness's .claude/hooks/*.sh expect, runs the relevant hooks, and translates their exit code into
# Cursor's {"permission": ...} output. Do not edit by hand; re-run port.py to regenerate.
import json, subprocess, sys, pathlib

event = sys.argv[1] if len(sys.argv) > 1 else ""
try:
    payload = json.load(sys.stdin)
except Exception:
    print(json.dumps({"permission": "allow"})); sys.exit(0)

# The hook runs with cwd = the project root (that is how Cursor invokes this adapter), and the hook
# is addressed by a RELATIVE path from there. Passing bash an absolute drive-letter path (C:\...)
# fails to resolve on Windows bash and would make the guard silently allow everything.
cwd = payload.get("cwd") or "."

if event == "shell":
    claude = {"cwd": cwd, "tool_name": "Bash",
              "tool_input": {"command": payload.get("command", "")}}
    names = ["guard-main-commit", "check-commit-msg", "protect-secrets"]
elif event == "read":
    claude = {"cwd": cwd, "tool_name": "Read",
              "tool_input": {"file_path": payload.get("file_path", "")}}
    names = ["protect-adr", "protect-secrets"]
else:
    print(json.dumps({"permission": "allow"})); sys.exit(0)

blob = json.dumps(claude)
for name in names:
    rel = f".claude/hooks/{name}.sh"
    if not (pathlib.Path(cwd) / rel).is_file():
        continue
    r = subprocess.run(["bash", rel], input=blob, capture_output=True, text=True, cwd=cwd)
    if r.returncode == 2:  # the hook blocked
        print(json.dumps({"permission": "deny",
                          "user_message": (r.stderr.strip() or f"{name} blocked this action.")}))
        sys.exit(0)
print(json.dumps({"permission": "allow"}))
'''


def port_codex_hooks(claude_hooks: pathlib.Path, dest: pathlib.Path, ext: str) -> pathlib.Path:
    """Codex payload == Claude payload, so register the existing hooks directly. No adapter."""
    dest.mkdir(parents=True, exist_ok=True)
    runner = "bash" if ext == "sh" else "powershell -NoProfile -ExecutionPolicy Bypass -File"

    def cmd(name: str) -> str:
        return f"{runner} .claude/hooks/{name}.{ext}"

    reg = {
        "hooks": {
            "PreToolUse": [
                {"matcher": "Bash",
                 "hooks": [{"type": "command", "command": cmd(n),
                            "statusMessage": f"harness: {n}"} for n in BASH_HOOKS]},
                {"matcher": "apply_patch",
                 "hooks": [{"type": "command", "command": cmd("protect-secrets"),
                            "statusMessage": "harness: protect-secrets"}]},
            ]
        }
    }
    out = dest / "hooks.json"
    out.write_text(json.dumps(reg, indent=2) + "\n", encoding="utf-8")
    return out


def port_cursor_hooks(dest: pathlib.Path) -> list[pathlib.Path]:
    dest.mkdir(parents=True, exist_ok=True)
    adapter = dest / "cursor-adapter.py"
    adapter.write_text(CURSOR_ADAPTER, encoding="utf-8")
    reg = {
        "version": 1,
        "hooks": {
            "beforeShellExecution": [{"command": f"python3 .cursor/hooks/{adapter.name} shell"}],
            "beforeReadFile": [{"command": f"python3 .cursor/hooks/{adapter.name} read"}],
        },
    }
    regfile = dest.parent / "hooks.json"
    regfile.write_text(json.dumps(reg, indent=2) + "\n", encoding="utf-8")
    return [regfile, adapter]


# --------------------------------------------------------------------------- self-test

def self_test() -> int:
    """Run the Cursor adapter logic against the documented sample payloads, in a temp harness, so
    the translation is exercised rather than trusted. Needs bash and a scaffolded harness on disk;
    if neither is present, this reports SKIP rather than a false pass."""
    import shutil
    here = pathlib.Path(__file__).resolve().parent
    scaffold = here / "scaffold.py"
    if not scaffold.is_file():
        print("  SKIP: scaffold.py not found next to port.py"); return 0

    # Scaffold into a workdir next to this script, not the system temp dir: on Windows the bash that
    # runs the hooks may not share a filesystem view with a Python temp dir, which would make the
    # hooks look broken when they are fine.
    wd = here.parent / ".port-selftest"
    def _force(fn, path, _e):
        import os as _os
        _os.chmod(path, 0o700); fn(path)
    if wd.exists():
        shutil.rmtree(wd, onexc=_force)
    wd.mkdir(parents=True)
    try:
        repo = wd / "repo"
        vars_json = wd / "vars.json"
        vars_json.write_text(json.dumps(_TEST_VARS), encoding="utf-8")
        r = subprocess.run([sys.executable, str(scaffold), "--target", str(repo),
                            "--vars", str(vars_json)], capture_output=True, text=True)
        if r.returncode != 0:
            print("  SKIP: could not scaffold a test harness:\n" + r.stdout[-400:]); return 0
        adr = repo / "docs/architecture/decisions"
        adr.mkdir(parents=True, exist_ok=True)
        (adr / "ADR-001.md").write_text("---\nstatus: Accepted\n---\n", encoding="utf-8")
        for c in (["git", "init", "-q", "-b", "main"], ["git", "config", "user.email", "e@e"],
                  ["git", "config", "user.name", "n"], ["git", "add", "-A"],
                  ["git", "commit", "-qm", "init"]):
            subprocess.run(c, cwd=str(repo), capture_output=True)

        port_cursor_hooks(repo / ".cursor" / "hooks")
        adapter = (repo / ".cursor/hooks/cursor-adapter.py").resolve()
        rcwd = repo.resolve().as_posix()

        cases = [
            ("shell", {"command": "cat .env", "cwd": rcwd}, "deny"),
            ("shell", {"command": "git commit -m 'x'", "cwd": rcwd}, "deny"),   # on main
            ("shell", {"command": "npm test", "cwd": rcwd}, "allow"),
            ("read",  {"file_path": f"{rcwd}/.env", "cwd": rcwd}, "deny"),
            ("read",  {"file_path": f"{rcwd}/src/x.ts", "cwd": rcwd}, "allow"),
        ]
        npass = nfail = 0
        for event, payload, want in cases:
            r = subprocess.run([sys.executable, str(adapter), event],
                               input=json.dumps(payload), capture_output=True, text=True,
                               cwd=str(repo))
            try:
                got = json.loads(r.stdout).get("permission")
            except Exception:
                got = f"BAD OUTPUT: {r.stdout!r} {r.stderr[:120]!r}"
            ok = got == want
            label = payload.get("command") or payload.get("file_path")
            print(f"  {'ok  ' if ok else 'FAIL'}  {event:5} {label:<40} -> {got} (want {want})")
            npass += ok
            nfail += not ok
        print(f"\n  {npass}/{len(cases)} adapter cases pass.")
        return 1 if nfail else 0
    finally:
        shutil.rmtree(wd, onexc=_force)


_TEST_VARS = {
    "vars": {k: "x" for k in [
        "PROJECT_NAME", "PROJECT_SLUG", "DEFAULT_BRANCH", "PR_OR_MR", "CI_PLATFORM", "HOSTING",
        "UNIT_FRAMEWORK", "E2E_FRAMEWORK", "COVERAGE_TARGET", "TEST_CMD", "LINT_CMD", "BUILD_CMD",
        "DB_RESET_CMD", "DEPLOY_CMD", "ORM", "COMMIT_SCOPES", "SOURCE_GLOBS", "UI_GLOBS", "DB_GLOBS",
        "TEST_GLOBS", "PII_OR_DATA", "ROUTING_TABLE", "AGENT_ROSTER_TABLE", "DEV_AGENT_NAME",
        "DOMAIN", "DOMAIN_DESCRIPTION", "MODULE_PATHS", "FR_LIST", "COMMIT_TYPES", "DB_RESET_PATTERN",
        "MODEL_PUBLIC", "MODEL_INTERNAL", "MODEL_CONFIDENTIAL", "MODEL_RESTRICTED", "DATA_RESIDENCY",
        "ALLOWED_LICENCES", "DENIED_LICENCES", "IP_OWNERSHIP_STATEMENT", "DEP_MANIFEST_GLOBS",
        "GATED_ACTIONS", "INCIDENT_CONTACT",
    ]},
    "flags": ["posix", "ui", "db", "ai"],
}
_TEST_VARS["vars"]["DEFAULT_BRANCH"] = "main"
_TEST_VARS["vars"]["HOOK_RUNNER"] = "bash"
_TEST_VARS["vars"]["HOOK_EXT"] = "sh"
_TEST_VARS["vars"]["SOURCE_GLOBS"] = '"src/**/*.ts"'
_TEST_VARS["vars"]["RESTRICTED_DENIES"] = '"Read(**/.restricted/**)",'


def port(target: pathlib.Path, tool: str) -> None:
    claude = target / ".claude"
    rules = claude / "rules"
    hooks = claude / "hooks"
    if not rules.is_dir():
        raise SystemExit(f"no {rules} - scaffold the Claude harness first (run harness-bootstrap).")
    ext = "sh" if (hooks / "protect-secrets.sh").is_file() else "ps1"

    if tool in ("cursor", "all"):
        r = port_cursor_rules(rules, target / ".cursor" / "rules")
        f = port_cursor_hooks(target / ".cursor" / "hooks")
        print(f"\nCursor:")
        print(f"  .cursor/rules/      {len(r)} rules (.md -> .mdc, paths: -> globs:)")
        print(f"  .cursor/hooks.json  registers the beforeShellExecution / beforeReadFile adapter")
        print(f"  {f[1].relative_to(target).as_posix()}  the adapter (Cursor payload -> harness hooks)")
        print(f"  note: Cursor's afterFileEdit is observational, so an edit to an Accepted ADR is")
        print(f"        flagged after the fact, not blocked before. Everything else blocks pre-hoc.")

    if tool in ("codex", "all"):
        h = port_codex_hooks(hooks, target / ".codex", ext)
        print(f"\nCodex:")
        print(f"  AGENTS.md           already generated by harness-bootstrap - Codex reads it natively")
        print(f"  {h.relative_to(target).as_posix()}   registers the existing hooks (Codex payload == Claude payload)")
        print(f"  note: Codex routes file edits through apply_patch (path inside tool_input.command),")
        print(f"        so protect-adr is best-effort there; the Bash-based guards are exact.")


def main() -> int:
    ap = argparse.ArgumentParser(description="Port a scaffolded harness to Cursor or Codex.")
    ap.add_argument("--target", type=pathlib.Path, help="repo that already has a scaffolded .claude/")
    ap.add_argument("--tool", choices=["cursor", "codex", "all"], default="all")
    ap.add_argument("--self-test", action="store_true", help="test the adapter on sample payloads")
    a = ap.parse_args()

    if a.self_test:
        print("Cursor adapter self-test:")
        return self_test()
    if not a.target:
        ap.error("--target is required unless --self-test")
    port(a.target.resolve(), a.tool)
    return 0


if __name__ == "__main__":
    sys.exit(main())
